# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run dev:prepare
      - run: npm run test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run build
      
      # Update the version in package.json
      - name: Update Version
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          VERSION=$(echo ${{ github.event.release.tag_name }} | sed 's/v//')
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/g" package.json
          if [ "$(git status --porcelain)" = "" ]; then
            echo "No changes to commit"
            exit 0
          fi
          git add .
          git commit -m "Bump version to $VERSION"
      
      - name: CHANGELOG.md
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          outputFile: CHANGELOG_NEW.md
      
      - name: Merge changelog
        run: cat CHANGELOG_NEW.md >> CHANGELOG.md
      
      - name: Adding commit
        run: |
          VERSION=$(echo ${{ github.event.release.tag_name }} | sed 's/v//')
          if [ "$(git status --porcelain)" = "" ]; then
            echo "No changes to commit"
            exit 0
          fi
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md according to $VERSION"
  
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}


      - name: Publishing the package
        run: npm publish 
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}